apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: gokube
  environment: production

namespace: gokube

images:
- name: ${DOCKER_USERNAME}/gokube
  newTag: latest 